### ISSUE TITLE
Consider removing highlightjs

### ISSUE THREAD

**Issue by ravron** [aos/temple#24]
Hugo has supported [Chroma](https://github.com/alecthomas/chroma) since version 0.28, released 2017-09-25. Chroma supports a [pretty wide array of languages](https://github.com/alecthomas/chroma#supported-languages), and it renders its highlighting at site build-time. That means clients don't need highlight.js scripts and pages will be both lighter and faster. For this reason I may remove highlight.js in my fork, and I'm curious if you would accept a PR that does the same in this repo. I totally understand if not — if for no other reason than it might require some changes to make your personal blog still look good. 

Let me know what you think @aos!

**Comment by aos** [comment]
Hey @ravron I didn't know about Chroma -- that's great. I've been wanting to remove `highlightjs` for the longest time since it's the only remaining JS left on this theme. If you look at my [blog](https://aos.github.io), you'll notice that most of the heaviness comes from highlightjs!

I'll look into Chroma! I think most importantly I want to make sure the highlighting color styles still match the blog theme. If you are considering doing this for your fork, I'd also accept a PR to look into your implementation of it.

Thanks a lot for doing all of this.

**Comment by aos** [comment]
This is great thank you! I'm very busy right now but will take a look at it sometime tomorrow or Friday

**Comment by aos** [comment]
Closing -- thanks to work by @ravron in #26
